cc_binary(
    name = "main",
    srcs = [
        "main.cpp"
    ],
    deps = [
        ":Adder",
    ],
)

cc_library(
    name = "Adder",
    srcs = [
        "Adder.cpp",
    ],
    hdrs = [
        "Adder.h",
    ],
)
